apache/cordova-cli

doc/platform.txt

This isn't for merging, it's more of a Request-For-Information/Feedback.
What do we support?
(Obviously we shouldn't document what we don't)

CB-7739 document installing specific version of platforms

---

doc/platform.txt
src/cli.js

CB-8227 CB-8237 CB-8238 Add --save option to 'cordova platform add', 
'cordova platform remove' and 'cordova platform update'

CB-8227 CB-8237 CB-8238 Add --save option to 'cordova platform add', 'cordova platform remove' and 'cordova platform update'

---

doc/requirements.txt
src/cli.js

This is implementation for [CB-8898](https://issues.apache.org/jira/browse/CB-8898) which adds `cordova requirements` command.
This PR requires https://github.com/apache/cordova-lib/pull/208 to be merged as well

CB-8898 Introduces `cordova requirements` command

---

doc/platform.txt
src/cli.js

The recommended method is to use `cordova platform add git_url#branch`

Removing the '--usegit' flag from `cordova platform`.

---

README.md
src/cli.js

[Jira issue](https://issues.apache.org/jira/browse/CB-10482)

CB-10482 Remove references to windows8 from cordova-lib/cli

---

doc/config.txt
doc/cordova.txt
package.json
spec/cli.spec.js
src/cli.js

CB-11982: rewrote tests for cordova config

---

src/cli.js

CB-12683: fixed error handling

---

doc/config.txt

Update cordova-cli docs for cordova config command. Include examples for browserify, fetch, and autosave and include options with a more detailed description.

CB-12693 : Update cordova-cli docs for cordova config command with descriptions and options

---

src/cli.js

All.
Added searchpath as a config option.
Manual tests.
- [ Y ] [Reported an issue](http://cordova.apache.org/contribute/issues.html) in the JIRA database
- [ Y ] Commit message follows the format: "CB-3232: (android) Fix bug with resolving file paths", where CB-xxxx is the JIRA ID & "android" is the platform affected.
- [ Y ] Added automated test coverage as appropriate for this change.

CB-12862 all: Added searchpath as a config option

---

.jshintignore
src/cli.js
src/telemetry.js

Removed .jshintignore file and removed unneeded references to jshint

CB-13274 : removed .jshintignore file and removed unneeded references to jshint

---

.travis.yml
appveyor.yml

CB-13501 : updated to include node 8

---

doc/config.txt
doc/cordova.txt
doc/platform.txt
doc/plugin.txt
doc/readme.md
spec/cli.spec.js
src/cli.js

CB-13055: removed nofetch option

---

doc/readme.md

Update readme.md - Proposal of corrections

---

bin/cordova

Cleanup application entry point

---

README.md

Docs
Updates the README to no longer reference JIRA
N/A

Update README to remove JIRA reference

---

spec/cli.spec.js
spec/help.spec.js

See https://github.com/apache/cordova-cli/pull/306#issuecomment-417190230

Fix tests after removing deprecated `raw` methods from lib

---

spec/cli.spec.js
spec/help.spec.js

- Minor fix
- Use promises for async tests (needed for #314)
- ES2015ify the tests since it's 2018 already

Minor test cleanup

---

doc/build.txt
doc/config.txt
doc/plugin.txt
doc/prepare.txt
doc/readme.md
doc/run.txt
spec/cli.spec.js
src/cli.js

GH-320 Remove support for browserify

---

spec/cli.spec.js
src/cli.js

Part of https://github.com/apache/cordova/issues/9

Remove support for fetch option

---

bin/cordova
npm-shrinkwrap.json
package.json

Fix issues in cordova@8.1.0

---

.travis.yml

since PR #343 was raised on 8.1.x branch

Cherry-pick GH-343 on master - check that bin/cordova works on Travis CI

---

doc/readme.md

Doc change only - no platforms affected
Doc change only
Reviewed the diff
Doc change only

Fix typo: "esecially" to especially

---

src/cli.js

Noticed an error message pointing to node 6.x and rewrote it a bit.

Update node depreaction notice message

---

doc/readme.md

Only the documentation is affected
The change is due to the issue https://github.com/apache/cordova-electron/issues/49
Resolves apache/cordova-electron#49
[x] Added "Electron" to the supported platforms
[x] Removed "Ubuntu" & "Blackberry10" from the suported platforms
[x] Removed the section "Deprecated platforms"
I previewed the changes. No changes in code base, so no tests within cordova itself.

Updated the supported platforms

---

doc/readme.md

only documentation
Line 86,87 is possible duplication to line 84, 85.
Reviewed the diff

docs(readme): remove duplicated instructions

---

package.json

Bumping to mark repo for next major
Changes the packages version.
- `npm t`

chore: bump version to 10.0.0-dev

---

package.json

Keep the testing tools updated.
Bump the `jasmine` dev dependencies. 
- `npm t`

chore: update testing (jasmine)

---

doc/platform.txt
doc/readme.md

Follow-up to https://github.com/apache/cordova-lib/pull/800

docs: undocument "platform check" command

---

doc/create.txt
src/cli.js

See https://github.com/apache/cordova-lib/pull/805

Remove support for <project>/.cordova/config.json

---

doc/readme.md

These instances had been missed in #475

docs(create): remove mentions of argument "config"

---

doc/readme.md

Following up to apache/cordova-lib#781

docs: undocument "plugin save" command

---

package.json
src/cli.js

- Bump Cordova-ESLint dependency & apply automated fix
- `npm run lint`

chore(eslint): bump to 3.0.0 w/ fix

---

package.json

- Cleanup the `package.json` data.
- Use Short Notation
- Set ASF as author

chore: cleanup package.json

---

package.json

Use Latest Dev Dependencies
- mock-stdin@^1.0.0
- nyc@^15.1.0
- rewire@^5.0.0
- `npm t`

breaking: bump dev dependencies

---

.npmignore

- Cleanup the Cordova CLI npm package by improve the npm ignore list
- `npm t`

chore: improve npm ignore

---

package-lock.json
package.json

- Use current Cordova Lib release 10.0.0
- `npm t`

breaking: bump cordova-lib@^10.0.0

---

package-lock.json
package.json

ALL
Closes #549 
```
SEMVER WARNING: Recommended action is a potentially breaking change
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Moderate      │ Command Injection                                            │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ systeminformation                                            │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ systeminformation                                            │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ systeminformation                                            │
├───────────────┼────────────────────────────────────────────── …
```

dep: systeminformation@^5.5.0

---

package-lock.json
package.json

Prepare for minor release
Bump package version
n/a

feat: bump package version to 11.1.0-dev

---

doc/readme.md
doc/telemetry.txt

all
Language was non-inclusive : 'he'
Changed gendered 'he' to 'they'

Remove unnecessary gendered text

---

package-lock.json
package.json

n/a
Use latest npm dependencies (minor+patch) for next minor release.
Bumped packages:
- `cordova-common@^4.1.0`
- `cordova-create@^4.1.0`
- `cordova-lib@^11.1.0`
- `systeminformation@^5.17.3`
Also rebuilt package-lock.json
`npm t`

dep(npm): bump to latest minor+patch w/ package-lock rebuild

---

package-lock.json
package.json

n/a
preparing for 12.0.0 release
bump package and package-lock
n/a

feat!: bump to 12.0.0-dev

---

.github/workflows/ci.yml
package-lock.json
package.json
src/cli.js
src/telemetry.js

n/a
Use latest possible dependencies
Bumped:
- `@cordova/eslint-config@^5.0.0`
- `jasmine@^4.6.0`
- `rewire@^6.0.0`
- `cordova-common@5.0.0`
- `fs-extra@11.1.1`
- `nopt@7.1.0`
- `semver@7.5.0`
- `systeminformation@5.17.12`
Set Node Engine Requirement `>=16.13.0`
Rebuilt package-lock
Update CI node supported testing.
`npm t`

dep!: bump all possible dependencies

---

package-lock.json
package.json

n/a
Use latest released Cordova packages
Bumped:
- `cordova-create@5.0.0`
- `cordova-lib@12.0.0`
`npm t`

dep!: bump cordova-create@5.0.0 & cordova-lib@12.0.0

---

doc/readme.md

Refactor the CLI Reference docs

doc: update & refactor cli reference

---

.github/workflows/release-audit.yml
.ratignore

n/a
Use latest release audit version dependencies
- bump Apache Creadur Rat 0.16.1
- use latest node
- fix .ratignore
Ran command locally & remote repo.

ci: update release audit workflow

---

package-lock.json
package.json
spec/cli.spec.js
src/cli.js
src/help.js
src/info.js

All
Closes GH-447.
* Update testing dependencies to latest versions
* Remove some unused dependencies
* Fix error in configstore delete code (GH-447)
Existing unit tests pass

chore: Update dependencies

---

.github/workflows/ci.yml
.github/workflows/release-audit.yml

all
Improve CI.
* Fix errors when dependabot PRs try to run tests in CI
* Add JavaScript code scanning with CodeQL
* Ran in CI, tests pass

chore(ci): Add code scanning & fix dependabot failures

---

package-lock.json

N/A
Cordova-cli depends on @babel/helpers@7.24.7 which has [vulnerability](https://github.com/advisories/GHSA-968p-4wvh-cqc8).
Ran `npm audit fix`
Ran `npm audit`

fix: bump @babel/helpers

---

.asf.yaml
.gitattributes
.github/workflows/ci.yml
.gitignore
.npmignore
.npmrc
.ratignore
CONTRIBUTING.md
README.md
RELEASENOTES.md
bin/cordova.cmd
cordova.js
doc/bash.md
doc/readme.md
scripts/cordova.completion
spec/cli.spec.js
spec/help.spec.js
src/cli.js
src/help.js
src/info.js

n/a
Cleanup and add missing license headers
- Fix formatting
- Add missing license headers
`rat`

chore: license headers
