apache/cordova-cli

- README.md
* Change `cordova command` to `cordova-cli command` to match the rest of the file
* Change `cordova library` to `Cordova library` to match the actual output
* Change `cordova project` to `Cordova project`
> CB-5316 Spell Cordova as a brand unless it's a command or script

- README.md
- Add Firefox OS as supported platform
- Change "App Manager" to the newer "WebIDE"
https://issues.apache.org/jira/browse/CB-8790
> CB-8790 - Add information about Firefox OS to the README

- doc/clean.txt
- doc/cordova.txt
- src/cli.js
This is an implementation for [CB-5578](https://issues.apache.org/jira/browse/CB-5578). Requires https://github.com/apache/cordova-lib/pull/241 to be merged first.
> CB-5578 Adds `clean` command to cordova-cli

- package.json
Typo introduced in e2f3cf6d403a9f23fa130ddfdc5fc74c69365f6e
Ping @nikhilkh
> Remove invalid space from license in package.json

- src/cli.js
Catch permissions error and print a workaround
[Jira issue](https://issues.apache.org/jira/browse/CB-10062)
> CB-10062 Error: EACCES: permission denied - update-notifier-cordova.json

- spec/cli.spec.js
[Jira issue](https://issues.apache.org/jira/browse/CB-11250)
`toMatch` expects regexp and the version can contain special symbols so using a check for substring.
> CB-11250 Fix CLI tests verifying the version

- spec/cli.spec.js
- src/cli.js
[Jira issue](https://issues.apache.org/jira/browse/CB-11262)
> CB-11262 Add a warning about prerelease lib/cli usage

- doc/readme.md
Added a section under plugins for dealing with plugin conflicts involving the new edit-config tag. References the plugin.xml guide for more information and examples.
> CB-11023 Add doc for conflicting plugins

- package.json
- spec/cli.spec.js
- src/cli.js
- src/telemetry.js
Node 4.x (which we're dropping in April 2018 as I recall) has native Promises, so let's use them.
> Use native Promises instead of Q

- bin/cordova
- package.json
- src/cli.js
Prior to this, the CLI would exit with `UnhandledPromiseRejectionWarning`
and a full stack trace when an error occurred.
With this change, set an error code indicating failure and only display
the error message by default. The stack trace is printed with --verbose.
Furthermore, the loud-rejection handler is registered to fail properly
if any rejected promises snuck past our handling.
> Have proper error code and message when failing

- src/cli.js
This PR fixes the bug where `cordova requirements` did not print out version numbers correctly.
Previously, it would print something like `ios-deploy: installed [object Object]`. Now it prints `ios-deploy: installed 1.9.2`.
This was a one line fix so none of the automated testing was run. I manually verified that the fix prints the version numbers correctly for the Android and iOS requirements.
Issue reported here: https://issues.apache.org/jira/browse/CB-13772
(No additional testing applicable)
> CB-13772: print version numbers correctly in "cordova requirements"

- doc/plugin.txt
- doc/readme.md
none
Remove (deprecate) `cordova plugin search` related help docs.
Related to PR: https://github.com/apache/cordova-lib/pull/671
> Deprecate 'cordova plugin search' command docs

- .travis.yml
- appveyor.yml
Until now, the CI test of this repo used the master versions of several dependencies instead of the specified versions.
I think testing the latest master versions together is already done by our nightly builds. And given the relatively low commit frequency of this repo, tests are triggered too seldom to achieve the desired effect.
This PR returns the CI configs to a normal state and cleans them up.
> Don't do 'nightly testing' & simplify CI configs

- src/cli.js
Resolves #314. Builds on #315.
> Remove callback parameter of main CLI function

- spec/cli.spec.js
Check the single commits for details.
This is also a setup for more telemetry-related stuff.
> cli.spec: telemetry-related improvements

- spec/cli.spec.js
This change makes _all_ `describe` blocks in cli.spec descendants of a
common top-level `describe` block which stubs any critical telemetry
methods.
Thus we ensure that telemetry is never collected during test runs.
All changes should be whitespace only.
> Stub telemetry calls during ALL tests

- src/cli.js
gracefully handle platforms that don't pass back requirements to check
- any platform that does not correctly return an array of requirements to check
- skips gracefully
> CB-13740 safe requirements check

- .travis.yml
Ensure that bin script actually runs on current Node.js version to detect and avoid bugs like #339
> Check that bin/cordova works on Travis CI

- package.json
according to procedure documented in:
- <https://github.com/apache/cordova-coho/blob/master/docs/tools-release-process.md#update-release-notes--version>
> GH-706 cordova-lib@8.1.1 dependency update (8.x only)

- npm-shrinkwrap.json
as generated by `npm install`
needed for `npm ci` to succeed on Node.js 8 & 10 on Travis CI
> Fix npm-shrinkwrap.json on 8.1.x only

- package.json
- spec/cli.spec.js
none
Cordova 9 Release
This PR contains final preparations for the Cordova 9 release goals. 
See [Cordova 9 Release Plan](https://github.com/apache/cordova/issues/10).
- Overload method `addLevel` to continue to support test spies on `logger[level]`.
- **Bumped Dependencies**
- `cordova-common@^3.1.0`
- `cordova-lib@^9.0.0`
- `editor@^1.0.0` (Added `^` only)
- `loud-rejection@^2.0.0`
- **Bumped ESLint dependencies with correction**
- `eslint@^5.15.2`
- `eslint-config-semistandard@^13.0.0`
- `eslint-config-standard@^12.0.0`
- `eslint-plugin-import@^2.16.0`
- `eslint-plugin-node@^8.0.1`
- `eslint-plugin-promise@^4.0.1`
- **Updated Dev Dependencies**
- `jasmine@^3.3.1`
- `npm t`
> Cordova CLI Release Preparation (Cordova 9)

- src/cli.js
The `cordova config list` command will be executed for any command with `list` as an argument, such as `cordova plugin list`. This PR fixes the if-statement to only apply to `cordova config list`.
This behavior becomes evident due to #418:
```
$ npm install -g cordova@latest
$ rm ~/.config/configstore/cordova-config.json
$ cordova plugin list
Current working directory is not a Cordova-based project.
Error: ENOENT: no such file or directory, open '/Users/ltm/.config/configstore/cordova-config.json'
```
The error is triggered by the `config list` command which is incorrectly being executed as part of the `plugin list` command.
> Fix config list command

- spec/cli.spec.js
- src/cli.js
Fixes #418 reported by @ltm 
This is a patch-level change.
Manual testing & modified the existing unit test.
> Fix `cordova config list` command

- spec/cli.spec.js
Simplify the code needed to spy on `CordovaLogger`. This reverts commit f626923431cb8e4cb3cd9e8668cf3f79757c233e.
> Cleaner solution to spy on latest CordovaLogger

- bin/cordova
all
Host OS: at least Windows
Properly output error strings
When command rejects with a string, it's special characters like newlines and tabs are not formatted,
Example:
```
cordova platform update cordova-ios --save
Using cordova-fetch for cordova-ios
Updating ios project...
CordovaError: Promise rejected with non-error: 'An in-place platform update is not supported. \nThe `platforms` folder is always treated as a build artifact.\nTo update your platform, you have to remove, then add your ios platform again.\nMake sure you save your plugins beforehand using `cordova plugin save`, and save a copy of the platform first if you had manual changes in it.\n\tcordova plugin save\n\tcordova platform rm ios\n\tcordova platform add ios\n'
at cli.catch.err …
```
> Handle output error strings

- package.json
- src/cli.js
https://github.com/apache/cordova/issues/79
- To warn users if they are on an unsupported node version.
- The supported node version requirement is `>=8`.
- Cordova will continue to work as usual on an unsupported version but with a warning.
- Added `semver` dependency.
- Update the satisfactory requirement. 
- Past checks warned when `v0.x` matched
- New checks warn when node version does not meet requirement: `>=8`.
Example: node process on version `6.17.1` will warn users:
```
Warning: Node.js v6.17.1 is no longer supported. Please upgrade to the latest Node.js version available (LTS version recommended).
```
- `npm t`
> chore: node warning on version < 8

- .gitignore
- .npmignore
- package.json
* Remove npm install warnings of a deprecated package.
* Be consistent with the packages we use in other repos.
* Remove `istanbul` package
* Add `nyc` package
* Update `.gitignore` and `.npmignore` to exclude the `.nyc_output`
* Update `npm test` to run the coverage instead of jasmine directly which produces the same results + coverage.
* `npm t`
* [Travis CI](https://travis-ci.org/erisu/cordova-cli/builds/583018998)
> chore: replace istanbul with nyc

- .travis.yml
Display coverage in GH
- Added install `codecov` step to `.travis.yml` and run `codecov` after script.
CI
> chore: add codecov to display coverage in GH

- package.json
- spec/cli.spec.js
- spec/telemetry.spec.js
The telemetry module had bad test coverage and I was about to start working on some improvements in that area. So I decided to first write some decent tests for it.
It might seem odd that I also tested some aspects of our dependency `insight`, but in some cases it was not at all clear what exactly would be happening. So I decided to just add some tests for interesting cases.
> Add unit tests for the telemetry module

- spec/cli.spec.js
- src/cli.js
- Adds deprecation warning for node between `>= 8` and  `<10`
- Adds Unit Tests
- npm t
> chore: node deprecation warning for <10

- doc/create.txt
- doc/readme.md
- src/cli.js
Apparently this once was an option for the create command. But there is no actual implementation for it, so using it would cause an error. Plus it's already deprecated.
Thus this could go in a patch release.
> Remove unsupported option --copy-from

- spec/telemetry.spec.js
- src/telemetry.js
`telemetry.track` is supposed to filter the arguments it receives and only pass truthy, non-empty arguments to `insight.track`. The purpose of this filtering is to ensure that the following call always produces nice results: https://github.com/apache/cordova-cli/blob/39141dd681b95e94ac9dea23a586f65589a2ba65/src/cli.js#L200
Without filtering and with `subcommand` unset, as would be the case when running e.g. `cordova help`, `help/undefined/successful` would be tracked. With filtering `help/successful` will be tracked.
This feature was broken (probably never worked as intended).
Fixing as discussed here: https://github.com/apache/cordova-cli/pull/471#pullrequestreview-302973791
Automated tests pass
> fix: argument filtering in telemetry.track

- spec/cli.spec.js
- spec/telemetry.spec.js
- src/telemetry.js
Some of the assertion made in the telemetry-related tests for the `cli` module were insufficient. Thus, telemetry calls that were supposed to be made actually never got out. The reason for this is, that these calls should be made in corner cases where the user decision is already or still set to _do-not-track_, but this value is about to change or has recently changed. But when `insight.optOut` is set to `true`, `insight.track()` is a no-op.
The exact failing tests can be seen in this [Travis CI log](https://travis-ci.org/raphinesse/cordova-cli/jobs/599844128#L227). The failing tests are:
- telemetry is collected when user runs `cordova telemetry off` while opted-in
- telemetry tracks opt-out that happened via `cordova telemetry off` even if user is NOT opted-in
- `telemetry.showPrompt` …
> Fix blocked telemetry calls

- doc/readme.md
`platform save` has already been removed, but there were some references to it left in the docs. This PR removes them.
> Undocument removed platform save command

- spec/cli.spec.js
Instead of muting the warning that Node.js displays about it.
> Avoid registering too many event listeners in tests

- doc/readme.md
This removes an instance of `platform save` from the docs that had been missed in #476.
> docs: undocument "platform save", again

- src/cli.js
This refactoring exposes that the `autosave` and `production` settings
in Cordova's config are actually always ignored.
> refactor: remove dead code & simplify

- spec/cli.spec.js
Replaces usage of the unsupported `autosave` configuration key in the
`cordova config` tests with a generic key `foo`.
Also see #483
> test(config): use generic config key name

- doc/config.txt
- doc/readme.md
Removes all documentation regarding the unsupported `autosave`
configuration setting.
Also see #483
> docs(config): undocument "autosave" setting

- package.json
- spec/cli.spec.js
- src/cli.js
This will allow us to remove the `cordova.create` stub from
`cordova-lib`.
Moreover it flattens our dependency graph by one level:
> refactor(create): depend directly on cordova-create

- src/cli.js
Expanding ~ is a shell feature and should not be done by us.
> refactor(create): do not expand ~ to $HOME anymore

- .eslintrc.yml
- package.json
- spec/.eslintrc.yaml
- spec/cli.spec.js
- src/cli.js
- src/telemetry.js
* replace eslint dependencies with @cordova/eslint-config
* update eslint config
* eslint corrections
* combine testing and core configs
- `npm t`
> refactor: eslint setup

- doc/create.txt
- doc/readme.md
- package.json
- spec/cli.spec.js
- src/cli.js
Have our CLI use the latest version of `cordova-create`.
Resolves apache/cordova-discuss#69
- remove support for --link-to option from code
- use --template option instead of --link-to in test
- remove --link-to option from docs
- update code & test to use new cordova-create interface
- Updated the existing tests
- Manually tested `cordova create app`
> refactor(create): use cordova-create 3.0.0-nightly

- src/cli.js
A few exceptions aside, the `cli` function checks if the current command exists as a property in `cordova-lib`. If not, it throws an error that the command is unsupported:
Cordova does not know config; try `cordova help` for a list of all the available commands.
Since the `config` and `create` commands are not handled by `cordova-lib` anymore and their previous implementations in `cordova-lib` have recently been removed, we need to make an exceptions for those commands.
> fix: cannot call config or create commands

- package.json
- src/cli.js
- src/info.js
- Migrate `cordova info` lib logic to CLI.
- This PR:
- closes https://github.com/apache/cordova-lib/issues/659
- closes https://github.com/apache/cordova-lib/issues/660
- closes https://github.com/apache/cordova-lib/issues/661
- closes https://github.com/apache/cordova-cli/issues/301
Migrating the `cordova info` logic to cli makes it easier to grab the CLI version. Even though we document to install cordova globally and that we can use a spawn to grab the version, this allows us to properly display the information level of the CLI and its dependencies if the CLI was installed locally to the project.
- Add `systeminformation` dependency to easily grab more detailed OS information
- Expanded on the printout for plugins
- Shorten the `package.json` output to snippet only the cordova data …
> feat: migrate "cordova info" lib logic to cli

- package.json
Use Latest Dependencies
- configstored@^5.0.1
- cordova-commond@^4.0.2
- cordova-created@^3.0.0
- cordova-libd@^9.0.1
- execad@^4.0.3
- insightd@^0.10.3
- loud-rejectiond@^2.2.0
- noptd@^4.0.3
- semverd@^7.3.2
- systeminformationd@^4.26.10
- update-notifierd@^4.1.0
- `npm t`
> breaking: bump dependencies

- src/cli.js
- The Node 8 Deprecation Transition flag has been unset because it has been completed.
- `npm t`
> chore: drop node-8 deprecation transition step

- CONTRIBUTING.md
- README.md
- doc/readme.md
- Commands formatted as code
- Add `build` command to list
- Better description for `prepare` and `compile`
- Fix bug in description of `prepare`
- Fix wrong command used in `cordova compile command` example/spec
- `Vs` => `vs.`
- Better formatting of mutually exclusive options
> Tiny CLI docs improvements

- spec/cli.spec.js
Two of the test fails when removing the `-dev` suffix.
After investigating, the `-dev` suffix will printout the `prerelease` warning but when the suffix is removed the warning is not printed. This shifts the indices on which the Node.js version validation message is displayed on.
This PR will take all the messages that are passed in the logger and concat them. It will check across all message for the unique snippet for the node validation message.
- `npm t`
> test: fix node.js version check

- src/info.js
Android
The `android` command is deprecated. When you run the command, it displays the following:
```
*************************************************************************
The "android" command is deprecated.
For manual SDK, AVD, and project management, please use Android Studio.
For command-line tools, use tools/bin/sdkmanager and tools/bin/avdmanager
*************************************************************************
Running /path/to/android-sdk/tools/bin/avdmanager list target
```
On many systems the `android` command isn't even in the PATH and so attempting to run the original command fails.
Replaced the `android` command with `avdmanager` as suggested by the displayed warning.
I made the change locally and tested by running `cordova info`.
(this issue was found by the team …
> (android) Replace deprecated `android` command with `avdmanager`

- package.json
See https://docs.npmjs.com/files/package.json#preferglobal
Related to https://github.com/apache/cordova/issues/55
> chore(pkg): remove deprecated no-op field "preferGlobal"

- package-lock.json
- package.json
All
systeminformation has a [documented](https://www.npmjs.com/advisories/1590) vulnerability for command injection involving the method `inetLatency()`.
I don't know if this method is used at all in any of our code paths, but better safe than sorry.
Updated `systeminformation` from version 4.26.10 to 4.34.6
Ran `npm test`.
> chore(dep): systeminformation@4.26.10 -> 4.34.6

- doc/plugin.txt
Closes #558 
Removes the `cordova plugin save` command from the help docs as the command has already been removed.
> Remove plugin save command from CLI help docs 

- package-lock.json
- package.json
Prepare for Cordova CLI 11 Release
Bump CLI version for next major release 11.0.0-dev.
- GH Actions
> chore: bump version to 11.0.0-dev

- .github/workflows/ci.yml
- package.json
Prepare for Cordova CLI 11 Release
* Drop node 10.0.0
* Bump node engine requirement to `>= 12.0.0`
* Update GitHub Actions CI testing to cover:
* 12.x
* 14.x
* 16.x
- GH Actions
> feat!: update node support

- package-lock.json
Prepare for Cordova CLI 11 Release
Rebuilt the `package-lock.json` file with v2
- GH Actions
> feat: rebuilt package-lock w/ v2

- package-lock.json
- package.json
Update to use latest npm dependencies
**Updated Packages:**
- `cordova-create@^4.0.0`
- `cordova-lib@^11.0.0`
- `execa@^5.1.1`
- `fs-extra@^10.0.0`
- `nopt@^5.0.0`
- `semver@^7.3.5`
- `systeminformation@^5.9.17`
- `update-notifier@^5.1.0`
- `jasmine@^3.10.0`
**Other Notes:**
I have temporary hard pinned the version of insight to the currently installed 0.10.3. This is to ensure that the package-lock.json will not contain the latest version which had major changes. The next PR will update insight to the latest release with the code changes.
- `insight@0.10.3`
I also did not upgrade the `configstore` and `execa` package the the latest release because it uses ESM which Cordova can not support at this time.
- `npm t`
> dep: bump package dependencies

- package-lock.json
- package.json
- spec/telemetry.spec.js
- src/telemetry.js
Update to use latest insight npm dependency
closes #566 
closes #567
Requires: #572
**Updated Packages:**
- `insight@^0.11.1`
**Other Notes:**
In this version, the `askPermission` no longer accepts a callback method. It was converted to be a promise. Also, if the process is running with the CI flag, the default returned result will become `undefined`.
- `npm t`
> dep: update insight w/ updated code usage

- cordova.js
- package-lock.json
- package.json
- src/cli.js
- src/help.js
- src/telemetry.js
Update to use latest eslint configs
Requires: #572 & #573
**Updated Packages:**
- `@cordova/eslint-config@^4.0.0`
**Other Notes:**
This PR also:
* Applied the automatic lint suggestions.
* Manually refactored the help method to pass linting.
- `npm t`
> dep: bump @cordova/eslint-config@^4.0.0

- package-lock.json
- package.json
n/a
* Update `package.json` and `package-lock.json` with latest minor and patch revisions
* `npm t`
* GitHub Actions
> dep(npm): bump dependencies to latest minor & patch revision

- .github/workflows/ci.yml
All
Node 12 is eol, we can continue to support it until our next major, but we don't need to keep running tests on it.
Update the coverage reporting
> update ci coverage and run ci on 14-18

- doc/cordova.txt
- doc/readme.md
- package-lock.json
- package.json
- src/cli.js
n/a
- Stop supporting the ability to notifiy users when a new version of CLI is available.
- Users must now manually review npmjs and Cordova's official blog for releases announcements.
- Resolves [moderate vuln.](https://github.com/advisories/GHSA-pfrx-2q88-qq97)
remove `update-notifier`
`npm t`
> feat!: remove update-notifier support

- src/cli.js
n/a
Prepare for the removal of calling binaries in the platform packages.
Use the platform API to handle listing out of targets.
This PR requires changes in https://github.com/apache/cordova-lib/pull/917
Since this breaking change needs the braking changes from the aboves Cordova-Lib PR, it is unessary to call the old method.
`npm t`
> feat!(run): call platform api to list targets

- package-lock.json
- package.json
Rolled dependencies to the latest non-breaking versions. Any dependency that has a major update were not touched.
Additionally `npm upgrade` was ran to update all sub-dependencies to the latest satisfactory version pins available. This solves most of the NPM audit issues.
There is 3 audit issues currently still standing, all from `insight` (and sub-dependencies of `insight`). This PR does not resolve issues from `insight` package.
> chore: Rolled dependencies to the latest non-breaking versions

- .github/workflows/rat.yml
- .github/workflows/release-audit.yml
- .ratignore
- NOTICE
- licence_checker.yml
n/a
Audit license headers on pull requests and commit pushes.
Created new workflow that runs Apache RAT.
- n/a
> ci(gh-action): add Apache RAT & package license checker workflow

- bin/cordova
this PR implements a more reliable way of setting the CLI's exit code in error cases.
Previously, I encountered this error when running the cli:
```console
$ cordova build
TypeError [ERR_INVALID_ARG_TYPE]: The "code" argument must be of type number. Received type string ('ERR_UNHANDLED_ERROR')
at process.set [as exitCode] (node:internal/bootstrap/node:123:9)
at /opt/nodejs/lib/node_modules/cordova/bin/cordova:33:22
```
With this version, I get to see the root problem:
```console
$ cordova build
Unhandled error. ('Parsing /home/me/hello/config.xml failed')
```
> remove potential error when setting exit code

- .github/workflows/ci.yml
- bin/cordova
- licence_checker.yml
- package-lock.json
- package.json
all
We want to do a new major version which drops the telemetry stuff, this is some other cleanup that should also be included in that next major.
* Updated package version to 13.0.0-dev
* Updated dependencies to latest compatible versions
* Removed the `loud-rejection` dependency because it's now default NodeJS behaviour
* Bumped the NodeJS engine requirement to Node 18
Note that we're bumping the NodeJS engine requirement, but the lower level modules (cordova-common, cordova-lib, etc.) have not had major versions published which bump that requirement yet. However, doing the bump here means that we should be able to pull in those major versions when they do happen, provided the visible API breaking change (to cordova-cli's perspective) is the NodeJS bump.
All unit tests pass
> chore!: Prepare for next major

- .github/workflows/release-audit.yml
n/a
Use `v1` tag for `apache-rat-action` to get latest updates
Changed from commit hash to tag.
n/a
> ci: use apache-rat-action@v1 (tag)

- package-lock.json
- package.json
n/a
nyc doesn't seem to be actively maintained. c8 is an alternative that relies on node itself to provide coverage information rather than trying to inject instrumentation into the code.
Move from nyc to c8
npm t
> chore(coverage): Move from nyc to c8 for code coverage
